# Gemma 1
- name: google/gemma-2b
  type: pretrained
  dtype: bfloat16
- name: google/gemma-2b-it
  type: instruction-tuned
  dtype: bfloat16
- name: google/gemma-7b
  type: pretrained
  dtype: bfloat16
- name: google/gemma-7b-it
  type: instruction-tuned
  dtype: bfloat16

# Gemma 2
- name: google/gemma-2-2b
  type: pretrained
  dtype: bfloat16
- name: google/gemma-2-2b-it
  type: instruction-tuned
  dtype: bfloat16
- name: google/gemma-2-9b
  type: pretrained
  dtype: bfloat16
- name: google/gemma-2-9b-it
  type: instruction-tuned
  dtype: bfloat16
- name: google/gemma-2-27b
  type: pretrained
  dtype: bfloat16
- name: google/gemma-2-27b-it
  type: instruction-tuned
  dtype: bfloat16